DECLARE @am_gw_api  VARCHAR(500);
SET @am_gw_api = (SELECT name FROM sys.foreign_keys WHERE parent_object_id = object_id('AM_GW_API_DEPLOYMENTS') AND referenced_object_id = object_id('AM_GW_PUBLISHED_API_DETAILS'));
EXEC ('ALTER TABLE AM_GW_API_DEPLOYMENTS DROP CONSTRAINT ' + @am_gw_api);

DECLARE @am_gw_arti  VARCHAR(500);
SET @am_gw_arti = (SELECT name FROM sys.foreign_keys WHERE parent_object_id = object_id('AM_GW_API_ARTIFACTS') AND referenced_object_id = object_id('AM_GW_PUBLISHED_API_DETAILS'));
EXEC ('ALTER TABLE AM_GW_API_ARTIFACTS DROP CONSTRAINT ' + @am_gw_arti);

DECLARE @am_api_ratings  VARCHAR(500);
SET @am_api_ratings = (SELECT name FROM sys.foreign_keys WHERE parent_object_id = object_id('AM_API_RATINGS') AND referenced_object_id = object_id('AM_API'));
EXEC ('ALTER TABLE AM_API_RATINGS DROP CONSTRAINT ' + @am_api_ratings);

DECLARE @am_api_comments  VARCHAR(500);
SET @am_api_comments = (SELECT name FROM sys.foreign_keys WHERE parent_object_id = object_id('AM_API_COMMENTS') AND referenced_object_id = object_id('AM_API'));
EXEC ('ALTER TABLE AM_API_COMMENTS DROP CONSTRAINT ' + @am_api_comments);

DECLARE @am_api_lc  VARCHAR(500);
SET @am_api_lc = (SELECT name FROM sys.foreign_keys WHERE parent_object_id = object_id('AM_API_LC_EVENT') AND referenced_object_id = object_id('AM_API'));
EXEC ('ALTER TABLE AM_API_LC_EVENT DROP CONSTRAINT ' + @am_api_lc);

DECLARE @am_sub_1  VARCHAR(500);
SET @am_sub_1 = (SELECT name FROM sys.foreign_keys WHERE parent_object_id = object_id('AM_SUBSCRIPTION') AND referenced_object_id = object_id('AM_API'));
EXEC ('ALTER TABLE AM_SUBSCRIPTION DROP CONSTRAINT ' + @am_sub_1);

DECLARE @am_sec_audit  VARCHAR(500);
SET @am_sec_audit = (SELECT name FROM sys.foreign_keys WHERE parent_object_id = object_id('AM_SECURITY_AUDIT_UUID_MAPPING') AND referenced_object_id = object_id('AM_API'));
EXEC ('ALTER TABLE AM_SECURITY_AUDIT_UUID_MAPPING DROP CONSTRAINT ' + @am_sec_audit);

ALTER TABLE AM_GW_API_DEPLOYMENTS ADD FOREIGN KEY (API_ID) REFERENCES AM_GW_PUBLISHED_API_DETAILS(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE AM_GW_API_ARTIFACTS ADD FOREIGN KEY (API_ID) REFERENCES AM_GW_PUBLISHED_API_DETAILS(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE AM_API_RATINGS ADD FOREIGN KEY(API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE AM_API_COMMENTS ADD FOREIGN KEY(API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE AM_API_LC_EVENT ADD FOREIGN KEY(API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE AM_SUBSCRIPTION ADD FOREIGN KEY(API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE AM_SECURITY_AUDIT_UUID_MAPPING ADD FOREIGN KEY (API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

-- you may encounter issues while adding foreign keys due data inconsistencies
ALTER TABLE AM_API_REVISION_METADATA ADD FOREIGN KEY(REVISION_UUID) REFERENCES AM_REVISION(REVISION_UUID) ON DELETE CASCADE;
ALTER TABLE AM_REVISION ADD FOREIGN KEY (API_UUID) REFERENCES AM_API(API_UUID) ON DELETE CASCADE;