ALTER TABLE AM_API_CATEGORIES DROP COLUMN TENANT_ID;

-- you may encounter issues while adding foreign keys due data inconsistencies
ALTER TABLE AM_API_REVISION_METADATA ADD FOREIGN KEY(REVISION_UUID) REFERENCES AM_REVISION(REVISION_UUID) ON DELETE CASCADE;
ALTER TABLE AM_REVISION ADD FOREIGN KEY (API_UUID) REFERENCES AM_API(API_UUID) ON DELETE CASCADE;

ALTER TABLE AM_GW_API_DEPLOYMENTS DROP FOREIGN KEY AM_GW_API_DEPLOYMENTS_ibfk_1 ;
ALTER TABLE AM_GW_API_DEPLOYMENTS ADD CONSTRAINT AM_GW_API_DEPLOYMENTS_ibfk_1 FOREIGN KEY (API_ID) REFERENCES AM_GW_PUBLISHED_API_DETAILS(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_GW_API_ARTIFACTS DROP FOREIGN KEY AM_GW_API_ARTIFACTS_ibfk_1;
ALTER TABLE AM_GW_API_ARTIFACTS ADD CONSTRAINT AM_GW_API_ARTIFACTS_ibfk_1 FOREIGN KEY (API_ID) REFERENCES AM_GW_PUBLISHED_API_DETAILS(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_API_RATINGS DROP FOREIGN KEY AM_API_RATINGS_ibfk_1;
ALTER TABLE AM_API_RATINGS ADD CONSTRAINT AM_API_RATINGS_ibfk_1 FOREIGN KEY(API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_API_COMMENTS DROP FOREIGN KEY AM_API_COMMENTS_ibfk_1;
ALTER TABLE AM_API_COMMENTS ADD CONSTRAINT AM_API_COMMENTS_ibfk_1 FOREIGN KEY(API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_API_LC_EVENT DROP FOREIGN KEY AM_API_LC_EVENT_ibfk_1;
ALTER TABLE AM_API_LC_EVENT ADD CONSTRAINT AM_API_LC_EVENT_ibfk_1 FOREIGN KEY(API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_SUBSCRIPTION DROP FOREIGN KEY AM_SUBSCRIPTION_ibfk_2;
ALTER TABLE AM_SUBSCRIPTION ADD CONSTRAINT AM_SUBSCRIPTION_ibfk_2 FOREIGN KEY(API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_SECURITY_AUDIT_UUID_MAPPING DROP FOREIGN KEY AM_SECURITY_AUDIT_UUID_MAPPING_ibfk_1;
ALTER TABLE AM_SECURITY_AUDIT_UUID_MAPPING ADD CONSTRAINT AM_SECURITY_AUDIT_UUID_MAPPING_ibfk_1 FOREIGN KEY (API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_APPLICATION_REGISTRATION DROP FOREIGN KEY AM_APPLICATION_REGISTRATION_ibfk_2 ;
ALTER TABLE AM_APPLICATION_REGISTRATION ADD CONSTRAINT AM_APPLICATION_REGISTRATION_ibfk_2 FOREIGN KEY (APP_ID) REFERENCES AM_APPLICATION(APPLICATION_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_APPLICATION_KEY_MAPPING DROP FOREIGN KEY AM_APPLICATION_KEY_MAPPING_ibfk_1 ;
ALTER TABLE AM_APPLICATION_KEY_MAPPING ADD CONSTRAINT AM_APPLICATION_KEY_MAPPING_ibfk_1 FOREIGN KEY (APPLICATION_ID) REFERENCES AM_APPLICATION(APPLICATION_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_SUBSCRIPTION DROP FOREIGN KEY AM_SUBSCRIPTION_ibfk_1 ;
ALTER TABLE AM_SUBSCRIPTION ADD CONSTRAINT AM_SUBSCRIPTION_ibfk_1 FOREIGN KEY (APPLICATION_ID) REFERENCES AM_APPLICATION(APPLICATION_ID) ON UPDATE CASCADE ON DELETE CASCADE;