ALTER TABLE AM_API ADD ORGANIZATION VARCHAR(100);
ALTER TABLE AM_APPLICATION ADD ORGANIZATION VARCHAR(100);
ALTER TABLE AM_API_CATEGORIES ADD ORGANIZATION VARCHAR(100);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[AM_SYSTEM_CONFIGS]') AND TYPE IN (N'U'))
CREATE TABLE AM_SYSTEM_CONFIGS
(
  ORGANIZATION     VARCHAR(100)            NOT NULL,
  CONFIG_TYPE      VARCHAR(100)            NOT NULL,
  CONFIGURATION    BLOB                    NOT NULL,
  PRIMARY KEY (ORGANIZATION,CONFIG_TYPE)
);